How it works responsive et dark/white mode friendly
itswilliambailey/bolero-music pull request #109
Opened 2020-12-07 17:42 UTC by remi-www

How it works sur laptop:
![localhost_3000_howitworks (2)](https://user-images.githubusercontent.com/70696190/101385012-7fda8800-38bb-11eb-9702-45820f31081e.png)

How it works sur tablette/smartphone... 
![localhost_3000_howitworks](https://user-images.githubusercontent.com/70696190/101385029-8537d280-38bb-11eb-84ba-8552b0af878d.png)

White mode: 
![localhost_3000_howitworks (1)](https://user-images.githubusercontent.com/70696190/101385280-df389800-38bb-11eb-9735-eee18fa862b5.png)

2020-12-07 18:35 UTC, itswilliambailey commented on app/assets/stylesheets/pages/_howitworks.scss
> +    max-width: 38vw;
Changer les vw en %

2020-12-07 18:35 UTC, itswilliambailey commented on app/assets/stylesheets/pages/_howitworks.scss
> +      max-width: 21vw;
Changer les vw en %

2020-12-07 18:35 UTC, itswilliambailey commented on app/assets/stylesheets/pages/_howitworks.scss
> +      max-width: 44vw;
Changer les vw en %

2020-12-07 18:36 UTC, itswilliambailey requested changes
Changer les vw en %

2020-12-08 10:52 UTC, remi-www commented
Check mon dernier commit, normalement tout est ok!

2020-12-08 11:56 UTC, merged